import Link from "next/link";

export default function Landing() {
  return <main className="landing">
    <header className="marketing-nav"><Link className="landing-brand" href="/"><span>W</span> Wavelength</Link><nav><a href="#comfort">Comfort</a><a href="#frequencies">Frequencies</a><Link href="/login">Log in</Link><Link className="nav-cta" href="/register">Create account</Link></nav></header>
    <section className="hero"><p className="hero-kicker"><i /> A real-time messenger tuned to you</p><h1>Meet people<br /><em>on your wavelength.</em></h1><p className="hero-copy">A calmer, more personal way to keep the conversations that matter in tune — whether you’re in motion, deep in focus, or winding down.</p><div className="hero-actions"><Link className="primary-cta" href="/register">Start a conversation <span>→</span></Link><Link className="secondary-cta" href="/login">I already have an account</Link></div><p className="no-card">Free to begin. No credit card, no noise.</p></section>
    <section className="signal-preview" aria-label="Wavelength interface preview"><div className="preview-top"><span /><span /><span /><b>Wavelength</b><small>now in sync</small></div><div className="preview-body"><aside><i /><i className="on" /><i /><i /></aside><section><div className="preview-title">Messages <small>⌘ K</small></div>{["Alma Reyes", "Design Sync", "Noah Bennett"].map((person, index) => <div className={`preview-chat ${index === 0 ? "chosen" : ""}`} key={person}><b>{person.slice(0, 2)}</b><span>{person}<small>{index === 0 ? "Let’s make it feel quieter." : "New ideas in the board"}</small></span>{index === 0 && <em>2</em>}</div>)}</section><article><header><b>AR</b><span>Alma Reyes<small>Active now</small></span></header><div className="preview-bubble theirs">I think we’re getting closer to the feeling.</div><div className="preview-bubble mine">The quiet parts are the point.</div><footer>Write a message… <b>↑</b></footer></article></div></section>
    <section id="comfort" className="landing-values"><p className="eyebrow">COMFORT, BY DESIGN</p><h2>Less interface.<br />More <em>presence.</em></h2><div className="value-grid"><article><span>01</span><h3>Find the signal</h3><p>Pulse Rail lets activity feel visible at a glance, so you spend less time scanning and more time responding.</p></article><article><span>02</span><h3>Leave room to think</h3><p>Undo Send, synced drafts, Focus Hours and full keyboard control remove the small frictions that add up.</p></article><article><span>03</span><h3>Make it yours</h3><p>Frequencies change not only the colour, but the density, contrast and motion of your whole space.</p></article></div></section>
    <section id="frequencies" className="frequency-landing"><div><p className="eyebrow">YOUR FREQUENCY</p><h2>It adapts to the way <em>you</em> show up.</h2><p>From the clear signal of Daylight to the low-sensory space of Focus Carrier, Wavelength adjusts with you, instantly.</p><Link href="/chats">Explore the workspace <span>→</span></Link></div><div className="frequency-samples"><article className="sample-midnight"><b>Midnight</b><span>Calm · deep focus</span></article><article className="sample-daylight"><b>Daylight</b><span>Instant · clear</span></article><article className="sample-dusk"><b>Dusk</b><span>Calm · low blue light</span></article><article className="sample-focus"><b>Focus Carrier</b><span>Minimal · spacious</span></article></div></section>
    <footer className="landing-footer"><Link className="landing-brand" href="/"><span>W</span> Wavelength</Link><p>Conversations, in your comfort zone.</p><Link href="/register">Create your account →</Link></footer>
  </main>;
}
