"use client";
import Link from "next/link";
import { useState } from "react";

type Kind = "groups" | "channels" | "contacts" | "saved" | "settings";
const icons: Record<Kind, string> = { groups: "◌", channels: "⌁", contacts: "◉", saved: "□", settings: "⊹" };
const settings = ["Account", "Privacy", "Notifications", "Sessions", "Appearance", "Language", "Security"];

export default function ProductArea({ title, description, kind, section }: { title: string; description: string; kind: Kind; section?: string }) {
  const [notice, setNotice] = useState(""); const [isOpen, setIsOpen] = useState(false);
  const titleCase = title.replace(/\b\w/g, char => char.toUpperCase());
  if (kind === "settings") return <main className="product-page settings-page"><header className="product-nav"><Link className="landing-brand" href="/chats"><span>W</span> Wavelength</Link><Link href="/chats">← Messages</Link></header><div className="settings-layout"><aside><p className="eyebrow">SETTINGS</p>{settings.map(item => <Link href={`/settings/${item.toLowerCase().replaceAll(" ", "-")}`} className={section === item.toLowerCase().replaceAll(" ", "-") ? "selected" : ""} key={item}>{item}<span>›</span></Link>)}</aside><section className="setting-content"><p className="eyebrow">SETTINGS / {titleCase.toUpperCase()}</p><h1>{titleCase}</h1><p>{description}</p>{section === "appearance" ? <Appearance onNotice={setNotice} /> : <GenericSettings section={titleCase} onNotice={setNotice} />}</section></div>{notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice("")}>Dismiss</button></div>}</main>;
  const labels: Record<Exclude<Kind, "settings">, string> = { groups: "Create group", channels: "Create channel", contacts: "New conversation", saved: "Save a note" };
  return <main className="product-page"><header className="product-nav"><Link className="landing-brand" href="/chats"><span>W</span> Wavelength</Link><nav><Link href="/chats">Chats</Link><Link href="/groups">Groups</Link><Link href="/channels">Channels</Link><Link href="/contacts">Contacts</Link><Link href="/settings/appearance">Settings</Link></nav></header><section className="area-hero"><span className="area-icon">{icons[kind]}</span><p className="eyebrow">YOUR {title.toUpperCase()}</p><h1>{title}</h1><p>{description}</p><button className="primary-cta" onClick={() => setIsOpen(true)}>{labels[kind]} <span>+</span></button></section><section className="area-list">{kind === "contacts" ? ["Alma Reyes", "Noah Bennett", "Jamie Huang", "Sasha Ortiz"].map((person, index) => <article className="person-row" key={person}><b>{person.split(" ").map(x => x[0]).join("")}</b><span><strong>{person}</strong><small>{index < 2 ? "Online now" : "Available recently"}</small></span><button onClick={() => setNotice(`Starting a conversation with ${person}`)}>Message</button></article>) : <EmptyState kind={kind} />}</section>{isOpen && <CreationDialog title={labels[kind]} kind={kind} onClose={() => setIsOpen(false)} onDone={value => { setIsOpen(false); setNotice(`${value} is ready.`); }} />}{notice && <div className="toast" role="status"><span className="toast-dot" />{notice}<button onClick={() => setNotice("")}>Dismiss</button></div>}</main>;
}

function EmptyState({ kind }: { kind: Kind }) { const copy = kind === "saved" ? "Save messages, links, and thoughts here — only you can see them." : kind === "groups" ? "Bring the right people together around one conversation." : "The signals you choose to tune into will appear here."; return <div className="area-empty"><span>{icons[kind]}</span><h2>Your space is ready.</h2><p>{copy}</p></div>; }
function CreationDialog({ title, kind, onClose, onDone }: { title: string; kind: Kind; onClose: () => void; onDone: (value: string) => void }) { const [value, setValue] = useState(""); return <div className="dialog-scrim" onMouseDown={onClose}><form className="creation-dialog" onMouseDown={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); if (value.trim()) onDone(value.trim()); }}><button type="button" className="dialog-close" onClick={onClose}>×</button><p className="eyebrow">{title.toUpperCase()}</p><h2>{kind === "groups" ? "Who should be in this?" : "Give it a clear name."}</h2><label>{kind === "saved" ? "Your note" : "Name"}<input autoFocus value={value} onChange={event => setValue(event.target.value)} placeholder={kind === "channels" ? "Design dispatch" : kind === "groups" ? "Weekend plans" : "A note to myself"} /></label><button className="auth-submit">Continue <span>→</span></button></form></div>; }
function GenericSettings({ section, onNotice }: { section: string; onNotice: (value: string) => void }) { return <div className="setting-stack"><article><h2>{section} preferences</h2><p>These controls are stored locally in this demo and are ready to connect to your profile settings endpoint.</p><label className="toggle-row">Keep this setting in sync across devices <input type="checkbox" defaultChecked /><span /></label><button className="subtle-button" onClick={() => onNotice(`${section} preferences saved`)}>Save changes</button></article></div>; }
function Appearance({ onNotice }: { onNotice: (value: string) => void }) { const [frequency, setFrequency] = useState("midnight"); const [density, setDensity] = useState("cozy"); const [motion, setMotion] = useState("calm"); function updateFrequency(next: string) { setFrequency(next); document.documentElement.dataset.frequency = next; } return <div className="appearance-studio"><article><h2>Frequency</h2><p>A visual and behavioral mode, not just a color scheme.</p><div className="appearance-frequency">{["midnight", "daylight", "dusk", "paper", "focus"].map(item => <button key={item} onClick={() => updateFrequency(item)} className={frequency === item ? "active" : ""}><i className={item} /><span>{item === "paper" ? "Paper Static" : item === "focus" ? "Focus Carrier" : item[0].toUpperCase() + item.slice(1)}</span></button>)}</div></article><article><h2>Comfort controls</h2><div className="radio-setting"><span>Density</span>{["compact", "cozy", "comfortable"].map(item => <button className={density === item ? "active" : ""} onClick={() => setDensity(item)} key={item}>{item}</button>)}</div><div className="radio-setting"><span>Motion</span>{["instant", "calm", "minimal", "none"].map(item => <button className={motion === item ? "active" : ""} onClick={() => setMotion(item)} key={item}>{item}</button>)}</div><label className="toggle-row">Use Atkinson Hyperlegible typeface <input type="checkbox" /><span /></label></article><article><h2>Theme Studio</h2><p>Build a Frequency that is entirely yours. Your preview changes while you adjust it.</p><div className="studio-preview"><span>Alma Reyes <i>Active now</i></span><b>That feels right.</b><em>Exactly the rhythm I wanted.</em></div><div className="studio-actions"><button className="subtle-button" onClick={() => onNotice("Custom Frequency saved locally")}>Save Frequency</button><button className="subtle-button" onClick={() => onNotice("Theme JSON export prepared")}>Export JSON</button></div></article></div>; }
